name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment: playwrightCI

    steps:
      # 1. Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      # 4. Install dependencies and only required Playwright browsers
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chromium --with-deps

      # 5. Create .env from secrets
      - name: Create .env from secrets
        run: |
          echo "VALID_USER=${{ secrets.VALID_USER }}" > .env
          echo "VALID_PASSWORD=${{ secrets.VALID_PASSWORD }}" >> .env
          echo "INVALID_USER=${{ secrets.INVALID_USER }}" >> .env
          echo "INVALID_PASSWORD=${{ secrets.INVALID_PASSWORD }}" >> .env

      # 6. Run Playwright tests
      - name: Run tests
        run: npm run test:ci

      # 7. Upload Allure results (always, even if tests fail)
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      # 8. Generate Allure report (always)
      - name: Generate Allure report
        if: always()
        run: npm run report:generate

      # 9. Deploy Allure report to GitHub Pages
      - name: Deploy Allure report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages

      # 10. Clean up .env
      - name: Remove .env
        if: always()
        run: rm -f .env
